### ISSUE TITLE
useless when called multiple times

### ISSUE THREAD

**Issue by raveren** [timacdonald/log-fake#23]
```php
    function test_asd()
    {
        Log::swap(new LogFake);

        $myFun = function ($i) {
            $a = random_int(0, 1000);
            var_dump('a', $a);
            Log::channel('just_for_testing')->debug($a, ['i' => $i]);
        };

        foreach ([1, 2, 3] as $i) {
            $myFun($i);

            Log::channel('just_for_testing')->assertLogged('debug',
                function ($message, $context) use ($i) {
                    var_dump($message, $context);

                    self::assertEquals($i, $context['i']);

                    return true;
                });
        }
    }
```

```
string(1) "a"
int(86)
int(86)
array(1) {
  ["i"]=>
  int(1)
}
string(1) "a"
int(368)
int(86)
array(1) {
  ["i"]=>
  int(1)
}

Failed asserting that 1 matches expected 2.
Expected :2
Actual   :1
Failed asserting that 1 matches expected 2.
Expected :2
Actual   :1
```

I just wasted an hour, thanks

**Comment by raveren** [comment]
Hey, you know I rolled my own quick solution to spy on uninjectable/static methods in tests, and had the same trouble until I changed

```php
            JustForTesting::shouldReceive('log')->withArgs(
                function ($blaId, $shippinIds) {
                    return true;
                });
```

into

```php
            JustForTesting::shouldReceive('log')->once()->withArgs(
                function ($blaId, $shippinIds) {
                    return true;
                });
```

notice the `->once()`

**Comment by timacdonald** [comment]
- [Relevant documentation](https://github.com/timacdonald/log-fake#assertloggedtimeslevel-times--1-callback--null)
- Matching Laravel *Fake APIs: [BusFake](https://github.com/laravel/framework/blob/3adf4363f68ab69c4ce33c2c539d2a927d553acf/src/Illuminate/Support/Testing/Fakes/BusFake.php#L105), [EventFake](https://github.com/laravel/framework/blob/3adf4363f68ab69c4ce33c2c539d2a927d553acf/src/Illuminate/Support/Testing/Fakes/EventFake.php#L113), [MailFake](https://github.com/laravel/framework/blob/3adf4363f68ab69c4ce33c2c539d2a927d553acf/src/Illuminate/Support/Testing/Fakes/MailFake.php#L75), [MailFake](https://github.com/laravel/framework/blob/3adf4363f68ab69c4ce33c2c539d2a927d553acf/src/Illuminate/Support/Testing/Fakes/NotificationFake.php#L80), [QueueFake](https://github.com/laravel/framework/blob/3adf4363f68ab69c4ce33c2c539d2a927d553acf/src/Illuminate/Support/Testing/Fakes/QueueFake.php#L53)

Refactored test to pass as expected...

```php
public function test_example()
{
    Log::swap(new LogFake);

    Log::channel('just_for_testing')->debug('second', ['i' => 2]);
    Log::channel('just_for_testing')->debug('first', ['i' => 1]);
    Log::channel('just_for_testing')->debug('third', ['i' => 3]);

    Log::channel('just_for_testing')->assertLoggedTimes('debug', 1, function (string $message, array $context): bool {
        return $context['i'] === 1;
    });
    Log::channel('just_for_testing')->assertLoggedTimes('debug', 1, function (string $message, array $context): bool {
        return $context['i'] === 2;
    });
    Log::channel('just_for_testing')->assertLoggedTimes('debug', 1, function (string $message, array $context): bool {
        return $context['i'] === 3;
    });
}
```

If you enjoy mocking, go for it. Absolutely works just as it does for all the other fakeable facades 👍
