### ISSUE TITLE
Call to undefined method TiMacDonald\Log\LogFake::getHandlers()

### ISSUE THREAD

**Issue by Denis4yk** [timacdonald/log-fake#3]
After upgrading to Laravel 5.7 from 5.6 started receiving this error

`Call to undefined method TiMacDonald\Log\LogFake::getHandlers()`

Here is where it appears
`collect(app('log')->getHandlers())...`

**Comment by timacdonald** [comment]
Can you give me some context around what you are doing with the handlers here? Perhaps the code snippet?

I'm just weighing up if the package could do with a fake handler, or if we just open that up the dev to implement.

**Comment by timacdonald** [comment]
I'm working on a Handler that will just proxy to the Log Fake, but if you are looking to test any specifics for a certain handler, you will need to work your own solution. I'll write up some documentation on how you can do this as well.

Hoping to have it ready soon.

**Comment by timacdonald** [comment]
Hey, I'm gonna close this as I haven't see any others with the issue. If anyone wants to submit a PR to fix this, please feel free.
