### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by marcelopm** [timacdonald/log-fake#34]
This a feature request for adding support for Laravel 9

**Comment by simonmaass** [comment]
<3 @timacdonald

**Comment by timacdonald** [comment]
on it's way folks. will be tagged in the coming days.

**Comment by OleKal** [comment]
Any news?

**Comment by marcelopm** [comment]
We decided to walk a way from dependencies that are easily replaceable to avoid this type of blocker on every major release of the framework.

To anyone who might be interested, the Log's facade has a listen method that allows capturing everything that gets logged:

```php
Log::listen(fn(MessageLogged $messageLogged) => $logged[] = $messageLogged->message);
```

That can be used in tests for making assertions.

**Comment by OleKal** [comment]
Thank you for the answer @marcelopm

**Comment by MattApril** [comment]
@marcelopm I've also personally had _some_ success with:

`Log::shouldReceive('error')->once()->with($message, $context)`

**Comment by timacdonald** [comment]
Hey folks, sorry for the delay on this one.

I've just tagged a 2.0 RC that you can take for a spin. Will tag an official v2 once some people have tested.

See: https://github.com/timacdonald/log-fake/releases/tag/2.0.0-rc1

Will flesh out the new features and changes. Hoping it'll mostly just be a noop upgrade for everyone really.

**Comment by timacdonald** [comment]
Hey folks, sorry for the delay.

Version 2 has been published 🎉 and supports Laravel 9. Please have a read over the docs though, as the log assertion API has changed.

Mostly, whenever you are asserting against the level, message,  or context you will want to update to a truth-test closure...


```diff
- Log::channel('slack')->assertLogged('alert', function ($message, $context) {
-     return str_contains($message, '5pm');
- });
+ Log::channel('slack')->assertLogged(function (LogEntry $log) {
+     return $log->level === 'alert' && str_contains($log->message, '5pm');
+ });
```

Sorry for the breaking changes, but makes things much nicer IMO.

Hope you enjoy it and sorry again for the slow release.
