### ISSUE TITLE
Support for Log::withContext($context)

### ISSUE THREAD

**Issue by Holonist** [timacdonald/log-fake#38]
We use Log::withContext($context)

This method was introduced in Laravel 8.49 and adds cascading context to all following log calls.
Unfortunately we need to wrap this in a try/catch in tests, otherwise it results in:

Error: Call to undefined method TiMacDonald\Log\LogFake::withContext()

This makes it impossible to test the context in logs that are dependent on this method call

**Comment by timacdonald** [comment]
Hey!

I've just tagged a 2.0 RC that you can take for a spin which has full support for context and even making assertions against the context at different points.

See: https://github.com/timacdonald/log-fake/releases/tag/2.0.0-rc1

Will tag a stable 2.0 shortly once it has been tested.

**Comment by timacdonald** [comment]
Version 2 is now released and has support for capturing context and also for asserting against that context.

Enjoy!
