### ISSUE TITLE
LogFake::bind() is not working with Laravel 8.x

### ISSUE THREAD

**Issue by SilvioDoMine** [timacdonald/log-fake#39]
After LogFake is installed via composer, the tests complains about the method bind() not exists. So we can't use this package as described in the docs.

![image](https://user-images.githubusercontent.com/20645369/187962053-a12df3c7-d22d-4574-a839-7f8ce1eee07d.png)

But even without the *bind()* the log isn't written on the log file (It was written before). Maybe this is just an old documentation?

**Comment by SilvioDoMine** [comment]
PHP version related. I was using 7.4, and 2.0.0 of this package require 8.0

**Comment by timacdonald** [comment]
Glad you got it sorted 😀
