### ISSUE TITLE
listen method support ?

### ISSUE THREAD

**Issue by mirzazeyrek** [timacdonald/log-fake#40]
Is there a way to keep Log::listen functionality after using LogFake::bind():

I do need such method to keep track on *all* unexpected logs during tests:

```
    /**
     * Fails the tests when an unexpected error is logged.
     */
    protected function setUpLogListener(): void
    {
        Log::listen(function (MessageLogged $msg) {
            if ($msg->level === 'error') {
                $this->assertTrue($this->expectErrorLog, "An unexpected error is logged: {$msg->message}");
            }
        });
    }
```

**Comment by timacdonald** [comment]
Wouldn't you do that with this library? With your example, if no log is created your test could still pass because the assertion is never run.

I would recommend using this library or not binding the fake logger.

```php
Log::bind();

// In your code...
Log::error('An unexpected error is logged: {$msg->message}');

// In your test...
Log::assertLogged(fn (LogEntry $log) => 
    $log->level === 'error' && $log->message === "An unexpected error is logged: {$msg->message}";
);
```

**Comment by mirzazeyrek** [comment]
I don't understand the logic of using assertLogged   for an unexpected error. 

May be I couldn't clarify the issue enough. I would like to fail any test if we log an error in the app. (Which is not using assertLogged because the error is unpredictable)
