### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by schonhoff** [timacdonald/log-fake#41]
Hey!

First of thanks for the great package. Helped my team test out so many different logs! Great work!

Do you plan the support for Laravel 10 with this package?

**Comment by it-can** [comment]
yes please!

**Comment by timacdonald** [comment]
https://github.com/timacdonald/log-fake/releases/tag/2.1.0

**Comment by schonhoff** [comment]
Thank you @timacdonald !
