### ISSUE TITLE
[Request] Support for Log::shareContext

### ISSUE THREAD

**Issue by crhg** [timacdonald/log-fake#44]
We use Log::shareContext, but it result in

Error : Call to undefined method TiMacDonald\Log\ChannelFake::shareContext()

Our use case is exactly the same as the example in the Laravel manual, and we use it to assign a unique id to each invocation.

[Contextual Information](https://laravel.com/docs/10.x/logging#contextual-information)[](https://laravel.com/docs/10.x/logging#contextual-information)

**Comment by riabiy** [comment]
Seems like a welcome inclusion : D
